version: '1.0'

services:
  postgres:
    image: postgres
    ports:
      - 5432:6432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword  

  "backend":
    build:
      network: host
      context: ./ 
      dockerfile: Dockerfile
    
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
  
    ports:
      - 3000:3000
    depends_on:
      - postgres    